use_modular_headers!

platform :ios, '10.0'

target 'SDMSearchMapKit_Example' do
  pod 'SDMSearchMapKit', :path => '../'

  target 'SDMSearchMapKit_Tests' do
    inherit! :search_paths

    
  end
end
